# Site settings
title: Alice's Portfolio Page
email: hexf0f8ff@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  James' Open Source Portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/NBighetti" # the base hostname & protocol for your site
twitter_username: NBighetti
github_username:  NBighetti

# Build settings
markdown: kramdown
